name: flake8

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    # make depends on poetry
    - name: Install dependencies
      run: |
        pip install poetry
        make install
    - name: Run linter
      run: make lint
